spring:
  application:
    name: Service interaction
  http:
    log-request-details: true
server:
  port: 8200
security:
  basic:
    enabled: false
  oauth2:
    client:
      grantType: authorization_code
      clientId: client
      clientSecret: password
      # 172.21.0.1:8090 ou minikube ip(192.168.99.100:30090) si le service tourne dans un container ou k8s, localhost sinon
      accessTokenUri: http://172.21.0.1:8090/auth/oauth/token
      userAuthorizationUri: http://172.21.0.1:8090/auth/oauth/authorize
      preEstablishedRedirectUri: http://172.21.0.1:8090/login
    resource:
      userInfoUri: http://172.21.0.1:8090/auth/user/me

url:
  # 172.20.0.1:8100 ou minikube ip(192.168.99.100:8100) si le service tourne dans un container ou k8s, localhost sinon
  service-utilisateur: http://172.20.0.1:8100/utilisateurs

logging:
#  file: /tmp/server.log
  level:
    org:
      springframework:
        web: DEBUG
